# Generated by Django 4.2.20 on 2025-09-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('schedule', models.CharField(default='To be announced', max_length=200)),
                ('description', models.TextField(default='No description provided.')),
            ],
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.RemoveField(
            model_name='gymsubscription',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='nutritionguide',
            name='description',
        ),
        migrations.RemoveField(
            model_name='nutritionguide',
            name='duration',
        ),
        migrations.AddField(
            model_name='gymsubscription',
            name='duration_months',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='nutritionguide',
            name='content_summary',
            field=models.TextField(default='Content coming soon.'),
        ),
        migrations.AlterField(
            model_name='gymsubscription',
            name='description',
            field=models.TextField(default='No description provided.'),
        ),
        migrations.AlterField(
            model_name='nutritionguide',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
