# Generated by Django 4.2.20 on 2025-09-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedbagitem',
            name='item_type',
            field=models.CharField(max_length=20),
        ),
    ]
