# Generated by Django 4.2.20 on 2025-09-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0002_alter_savedbagitem_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedbagitem',
            name='item_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='savedbagitem',
            name='item_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
